matapp/urls.py
from django.contrib import admin
from matapp.views import *
from matpro.settings import *
from django.views.generic import View
from django.conf import settings
from django.contrib.auth.decorators import login_required

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static


admin.autodiscover()
urlpatterns = patterns('',
    # Examples:
    url(r'^login/$', 'matapp.views.log', name='log'),
    url(r'^$', userform.as_view(),name='userform'),
    url(r'^adv_info/$', advform.as_view(),name='advform'),
    url(r'^fulldet/(?P<pk>[-\w]+)/$', fulldet.as_view()),
    url(r'^dummy/$', 'matapp.views.dummy',name='dummy'),
    url(r'^logout/$', 'matapp.views.user_logout',name='logout'),
    url(r'^approve/(?P<pk>[-\w]+)/$', approve.as_view()),
    url(r'^delete/(?P<pk1>[-\w]+)/(?P<pk2>[-\w]+)/(?P<pk3>[-\w]+)/(?P<pk4>[-\w]+)/$', delete.as_view()),
    url(r'^search/$', 'matapp.views.search',name='search'),
    
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^admin/', include(admin.site.urls)),    
)

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns +=staticfiles_urlpatterns()

matpro/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns("",
    #url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),   
    url(r"^matrimony/", include("matapp.urls")),
    url(r"^", include("myapp.urls")),
    
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

myapp/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from myapp.views import *
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'myapp.views.Index', name='home'),
    url(r'^state_admin_login$', view=State_login.as_view(),name='state_admin_login'),
	url(r'^about$', ('myapp.views.About'),name='about_page'),
	url(r'^services$', ('myapp.views.Services'),name='services_page'),
	url(r'^message$', ('myapp.views.Message'),name='message_page'),
	url(r'^documents$', ('myapp.views.Documents'),name='documents_page'),
	url(r'^gallery$', ('myapp.views.Gallery'),name='gallery_page'),
	url(r'^membership$',view=Membership.as_view(), name='print'),
	url(r'^contact$', ('myapp.views.Contact'),name='contact_page'),
	url(r'^members_all$', ('myapp.views.Members_all'),name='members_all_page'),
	url(r'^get_id$',view=GetId.as_view(), name='print'),
	url(r'^chaining/', include('smart_selects.urls')),
    # url(r'^mysite/', include('foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

matapp/models.py
from django.db import models
from django.db.models.fields import *
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from multiselectfield import MultiSelectField
from smart_selects.db_fields import ChainedForeignKey
from django.conf import settings
# from app.models import Member

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
gender_choice=(
	('M','MALE'),
	('F','FEMALE'),	
)
status_choice=(('UNMARRIED','UNMARRIED'),
	('WIDOW/WIDOWER','WIDOW/WIDOWER'),
	('DIVORCED','DIVORCED')
)
mt_choice=(('TAMIL','TAMIL'),
	('TELEGU','TELEGU'),
	('MALAYALAM','MALAYALAM'),
	('KANNADA','KANNADA'),
	('OTHERS','OTHERS'),
)
crt_choice =(('SELF','SELF'),
	('PARENTS','PARENTS'),
	('SIBLINGS','SIBLINGS'),
	('FRIENDS','FRIENDS'),
	('RELATIVES','RELATIVES'),	
)
height_choice=(
	('4','4 feet'),
	('4.1','4 feet 1 inches'),
	('4.2','4 feet 2 inches'),
	('4.3','4 feet 3 inches'),
	('4.4','4 feet 4 inches'),
	('4.5','4 feet 5 inches'),
	('4.6','4 feet 6 inches'),
	('4.7','4 feet 7 inches'),
	('4.8','4 feet 8 inches'),
	('4.9','4 feet 9 inches'),
	('4.10','4 feet 10 inches'),
	('4.11','4 feet 11 inches'),
	('5','5 feet'),
	('5.1','5 feet 1 inches'),
	('5.2','5 feet 2 inches'),
	('5.3','5 feet 3 inches'),
	('5.4','5 feet 4 inches'),
	('5.5','5 feet 5 inches'),
	('5.6','5 feet 6 inches'),
	('5.7','5 feet 7 inches'),
	('5.8','5 feet 8 inches'),
	('5.9','5 feet 9 inches'),
	('5.10','5 feet 10 inches'),
	('5.11','5 feet 11 inches'),
	('6','6 feet'),
	('6.1','6 feet 1 inches'),
	('6.2','6 feet 2 inches'),
	('6.3','6 feet 3 inches'),
	('6.4','6 feet 4 inches'),
	('6.5','6 feet 5 inches'),
	('6.6','6 feet 6 inches'),
	('6.7','6 feet 7 inches'),
	('6.8','6 feet 8 inches'),
	('6.9','6 feet 9 inches'),
	('6.10','6 feet 10 inches'),
	('6.11','6 feet 11 inches'),
	('7','7 feet'),
	('7.1','7 feet 1 inches'),
	('7.2','7 feet 2 inches'),
	('7.3','7 feet 3 inches'),
	('7.4','7 feet 4 inches'),
	('7.5','7 feet 5 inches'),
	('7.6','7 feet 6 inches'),
	('7.7','7 feet 7 inches'),
	('7.8','7 feet 8 inches'),
	('7.9','7 feet 9 inches'),
	('7.10','7 feet 10 inches'),
	('7.11','7 feet 11 inches'),

)
fam_type_choice = (
	('J','Joint Family'),
	('N','Nuclear Family'),

)

job_choice = (
	('S','Self-Employed'),
	('G','Govt Employee'),
	('P','Private'),

)

star_choice = (
	('Aswini ','Aswini '),
	('Bharani','Bharani'),
	('Kritika','Kritika'),
	('Rohini','Rohini'),
	('Mrigashira','Mrigashira'),
	('Ardra','Ardra'),
	('Punarvasu','Punarvasu'),
	('Pushya','Pushya'),
	('Aslesha','Aslesha'),
	('Magha','Magha'),
	('Poorvaphalguni','Poorvaphalguni'),
	('Uttaraphalguni','Uttaraphalguni'),
	('Hasta','Hasta'),
	('Chitra','Chitra'),
	('Swati','Swati'),
	('Vishakha','Vishakha'),
	('Anuradha','Anuradha'),
	('Jyehstha','Jyehstha'),
	('Moola','Moola'),
	('Poorvashadha','Poorvashadha'),
	('Uttarashadha','Uttarashadha'),
	('Shravana','Shravana'),
	('Dhanshita','Dhanshita'),
	('Satabisha','Satabisha'),
	('Poorvabhadrapada','Poorvabhadrapada'),
	('Uttarabhadrapada','Uttarabhadrapada'),
	('Revati','Revati')


)

raasi_choice = (
	('Mesham','Mesham'),
	('Rishabam','Rishabam'),
	('Mithunam','Mithunam'),
	('Katakam','Katakam'),
	('Simmam','Simmam'),
	('Kanni','Kanni'),
	('Thulam','Thulam'),
	('Vritchigam','Vritchigam'),
	('Dhanusu','Dhanusu'),
	('Magaram','Magaram'),
	('Kumbam','Kumbam'),
	('Meenam','Meenam')
)

appr_choice = (
	('Yes','Yes'),
	('No','No')
)

class District(models.Model):
	id= models.AutoField(primary_key=True)
	district = models.CharField(max_length=50)

	def __unicode__(self):
		return u"%s" %(self.district)

class Religion(models.Model):
	id= models.AutoField(primary_key=True)
	religion = models.CharField(max_length=50)

	def __unicode__(self):
		return unicode(self.religion)

class Community(models.Model):
   community = models.CharField(max_length=100)
   religion = models.ForeignKey('Religion')
   def __unicode__(self):
       return unicode(self.community)

class Subcaste(models.Model):
	id= models.AutoField(primary_key=True)
	subcaste = models.CharField(max_length=50)
	community = models.ForeignKey(Community,verbose_name=u"Community")

	def __unicode__(self):
		return unicode(self.subcaste)

class Degree(models.Model):
	id= models.AutoField(primary_key=True)
	degree = models.CharField(max_length=50)

	def __unicode__(self):
		return u"%s" %(self.degree)

class Userprofile(models.Model):
	def save(self):
		if not self.reg_no:
			ct_own = Userprofile.objects.all().count()+1
			ct = '%06d' % ct_own
			comb='TNGAM'+ct+self.gender 
			self.reg_no = comb
		super(Userprofile, self).save()
	reg_no = models.CharField(max_length=12,blank=True,null=True)    
	bridename = models.CharField(max_length = 100, verbose_name=u"Bride/ Bride Grooms Name")
	pf_creator = models.CharField(choices=crt_choice,max_length=70,verbose_name=u"Profile Creator")
	user = models.OneToOneField(User)
	gender = models.CharField(choices=gender_choice,max_length=10,verbose_name=u"Gender")
	dob = models.DateField(blank=True, null=True,verbose_name=u"Date of Birth")
	status = models.CharField(choices= status_choice,max_length=15,verbose_name=u"Marital Status")
	religion = models.ForeignKey(Religion,verbose_name=u"Religion")
	community = ChainedForeignKey(Community,chained_field='religion',
											chained_model_field='religion',
											auto_choose=True,blank=True,null=True)
	subcaste = ChainedForeignKey(Subcaste,	chained_field='community',
			                                chained_model_field='community',
			                                auto_choose=True,
			                                blank=True,
			                                null=True)
	mother_tongue = models.CharField(choices= mt_choice,max_length=15,verbose_name=u"Mother Tongue")
	district = models.ForeignKey(District,verbose_name=u"District")
	mobile = PhoneNumberField(verbose_name=u"Mobile",max_length=13)
	appr_status = models.CharField(choices=appr_choice,max_length=3,default='No')
	def __unicode__(self):
		return u'%s %s %s %s %s' % (self.reg_no, self.user, self.dob, self.religion,
		self.district)

import os
def get_path(instance, filename):
    ext = filename.split('.')[-1]
    d = str(filename)
    d1 = os.path.splitext(d)[0]
    # d2 = instance.id
    filename = "%s.%s" % (d1,ext)
    return os.path.join('admin_folder', filename)

def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        kb_limit = 60
        Kilobyte_limit = 1024 *60
        if filesize > Kilobyte_limit:
            raise ValidationError("Max file size is %sKB" % str(kb_limit))

class Userprofile_personalinfo(models.Model):
	user_key = models.ForeignKey(Userprofile)
	photo1 = ProcessedImageField(upload_to = get_path,
                                 processors=[ResizeToFill(1740, 2370)],
                                 format='JPEG',
                                 options={'quality': 60},
                                 blank=True,
                                 null=True,verbose_name=u"Photograph")
	photo2 = ProcessedImageField(upload_to=get_path,
                                 processors=[ResizeToFill(125, 125)],
                                 format='JPEG',
                                 options={'quality': 30},
                                 blank=True,
                                 null=True,)
	height = models.CharField(choices=height_choice,max_length=70,verbose_name=u"Height")
	about = models.TextField(blank=True,null=True,verbose_name=u"About me")
	high_edu = models.ForeignKey(Degree,verbose_name=u"Highest Education")
	job = models.CharField(choices=job_choice,max_length=50,blank=True,null=True,verbose_name=u"Job Details")
	dr_no = models.CharField(max_length=200,blank=True,null=True,verbose_name=u"Door No. & Street")
	city = models.CharField(max_length = 100,verbose_name=u"City")
	district = models.ForeignKey(District)
	state =  models.CharField(default='TamilNadu',max_length=50,)
	star = models.CharField(choices=star_choice,max_length=50,blank=True,null=True)
	raasi = models.CharField(choices=raasi_choice,max_length=50,blank=True,null=True)
	gothram = models.CharField(max_length=50,blank=True,null=True)

class Userprofile_familyinfo(models.Model):
	user_key = models.ForeignKey(Userprofile)
	sister = models.IntegerField()
	brother = models.IntegerField()
	fam_type = models.CharField(choices=fam_type_choice,max_length=50,verbose_name=u"Family Type")
	par_phone = PhoneNumberField(max_length=13,verbose_name=u"Parents Phone Number")
	ref_by = models.CharField(max_length=100,verbose_name=u"Referred By")


	

	

matapp/forms.py
from matapp.models import *
from django import forms
from django.contrib.auth.models import User
# from captcha.fields import CaptchaField
# from haystack.forms import SearchForm


# class StudentForm(forms.ModelForm):
# 	class Meta:
# 		model = Video

# class NewsForm(forms.ModelForm):
# 	class Meta:
# 		model = News

class UserForm(forms.ModelForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'special'}))
	password = forms.CharField(max_length=60, widget=forms.PasswordInput())
	# captcha = CaptchaField()
	class Meta:
		model = User
		fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
	dob = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
	class Meta:
		model = Userprofile
		fields = (
			'bridename',
			'pf_creator',
			'gender',
			'dob',
			'status',
			'religion',
			'community',
			'subcaste',
			'mother_tongue',
			'district',
			'mobile')

class User_PersonalForm(forms.ModelForm):	
	class Meta:
		model = Userprofile_personalinfo
		exclude = ()

class User_FamilyForm(forms.ModelForm):	
	class Meta:
		model = Userprofile_familyinfo
		exclude = ()

# class PasswordResetRequestForm(forms.Form):
#     email_or_username = forms.CharField(label=("Email Or Username"), max_length=254)

matapp/templates/base.html
<!DOCTYPE html>
{% load widget_tweaks %}
<html>
<head>
	<title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  

<script src="//code.jquery.com/jquery-1.10.2.js"></script><!-- added for SmartSelects -->

<!-- added for formance input mask -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="{{STATIC_URL}}formance.min.js"></script>

<!-- added for django inputmask -->
<script src="{{STATIC_URL}}input-mask/jquery.inputmask.js"></script>
<script src="{{STATIC_URL}}input-mask/jquery.inputmask.date.extensions.js"></script>

<script type="text/javascript">
  $(function() {
                //Datemask dd/mm/yyyy
                $("#datemask").inputmask("dd-mm-yyyy", {"placeholder": "dd-mm-yyyy"});
                //Datemask2 mm/dd/yyyy

                $("[data-mask]").inputmask();

                //Date range as a button

            });
</script>

<script>
    $( function() {
      $("input[type='submit']").prop("disabled", true); // disable the submit button
      $("input.date_format").formance("format_dd_mm_yyyy") // setup the formatter
                             .on( 'keyup change blur', function (event) { // setup the event listeners to validate the field whenever the user takes an action
                               if ( $(this).formance('validate_dd_mm_yyyy') )
                                 $("input[type='submit']").prop("disabled", false); // enable the submit button if valid phone number
                               else
                                 $("input[type='submit']").prop("disabled", true); // disable the submit button if invalid phone number
                             });
    });
</script>
<style type="text/css">
form {
  position: relative;
  width: 500px;
  margin: 30px auto;
  font-size : 12px;
  background: rgba(192,192,192,0.8);
  padding: 0px 22px;
  border: 1px solid;
  border-top-color: rgba(255,255,255,.4);
  border-left-color: rgba(255,255,255,.4);
  border-bottom-color: rgba(60,60,60,.4);
  border-right-color: rgba(60,60,60,.4);
}
body {
  background: url({{ MEDIA_URL }}indian-marriage.jpg) no-repeat center center fixed;
    -moz-background-size:100% 100%;
    -webkit-background-size:100% 100%;
    background-size:100% 100%;
 
  font-family: "Open Sans Condensed", sans-serif;
}
.title{
  font-size: 20px;
  float:center;
  color : white;
  font-weight: bold;
  vertical-align: middle;
}

.error_message{
  color : crimson;
}
.titlebar{
  height : 100px;
  width : auto;
  position : fixed;
}
.logo{
  width : 100px;
  height: 90px;
}

 .iconDetails {
 margin-left:2%;
float:left; 
height:40px;
width:40px; 
} 

.container2 {
  width:100%;
  height:auto;
  
  /*background-color:;*/
  /*position: fixed;*/

}

h4 {
    margin:0px;
}


.header {
      background: -moz-linear-gradient(left, rgba(255,255,255,1) 4%, rgba(255,255,255,1) 11%, rgba(255,255,255,0) 100%); /* FF3.6-15 */
    background: -webkit-linear-gradient(left, rgba(255,255,255,1) 4%,rgba(255,255,255,1) 11%,rgba(255,255,255,0) 100%); /* Chrome10-25,Safari5.1-6 */
    background: linear-gradient(to right, rgba(255,255,255,1) 4%,rgba(255,255,255,1) 11%,rgba(255,255,255,0) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#00ffffff',GradientType=1 ); 
      
    }
</style>
</head>
<body>


<div class='container2'>
  <div  class= "header" style = "position:fixed;width:90%;height:100px;padding:1px;z-index: 1;">

    <div style="margin-top:0px;">
      <img src="{{STATIC_URL}}user.png" style="height:98px;width:80px;border-radius:50%" class="iconDetails"/>
    </div>  
    <div style='margin-left:100px;margin-top:0px;' >
      <span style="font-weight:bold; color:black;">
        <center>
          <span style="font-size:30px;" class="threedee">
            தமிழ்நாடு அரசு எஸ்சி/எஸ்டி அலுவலர் நலச்சங்கம்
          </span><br>
          <span style="font-size:15px;">
            பதிவு எண்
          </span>
          <span style="font-size:10px;">
            -58/1976
          </span>
        </center>
      </span>
    </div>

    <div style="float:right;font-size:.6em">
      <a href="/matrimony/login/"><button class="btn btn-danger" style="background-color:crimson;" >Log in</button></a>
    </div>
    <div style="float:right;margin-right:10px;">
      <a href="/matrimony/search/"><button class="btn btn-danger" style="background-color:crimson;" >Search</button></a>
    </div>
  </div>
</div>
<br>

{% block content %}

{% endblock %}


  
</div>
</body>
</html>

matapp/templates/register.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content%}
<style>
form{
  border-radius:10px;
}
.control-label{
  font-size: 10px;
}
.form-control{
  font-size: 10px;
}
.form-horizontal .control-label{
    text-align: left;
}

</style>
<div class="main-content" style='margin-top:100px;'>
<form action='' id="frm" class="form-horizontal" autocomplete="off" method=POST enctype="multipart/form-data"> {% csrf_token %}
<center> <h3><b style="color:crimson;">Register</b></h3></center>
  
  <!-- Userprofile form -->
  <div class="form-group">
    <label class="control-label col-sm-5" for="email">Bride/Bride Groom Full Name:</label>
    <div class="col-sm-7">
      <script type="text/javascript">
        function caps(x){
          document.getElementById("id_bridename").value = x.toUpperCase();;
        }     
      </script>
      {{ test1.bridename|add_class:'form-control'|attr:"oninput:caps(this.value);"|attr:"placeholder:Initials at end" }}
    </div>
    <span class="error_message">{{ profile_form.bridename.errors }}</span>  
    
  </div>


  <div class="form-group">
    <label for="id_pf_creator" class="control-label col-sm-5">Profile Created By:</label> 
      <div class="col-sm-7">
        <select class="form-control" id="id_pf_creator" name="pf_creator" placeholder="pf_creator">
          <option value="" selected="selected">---------</option>
          <option value="SELF">SELF</option>
          <option value="PARENTS">PARENTS</option>
          <option value="SIBLINGS">SIBLINGS</option>
          <option value="FRIENDS">FRIENDS</option>
          <option value="RELATIVES">RELATIVES</option>
        </select>
      </div>
    <span class="error_message">{{ profile_form.pf_creator.errors }}</span>
  </div>

  <div class="form-group">
    <label for="id_gender" class="control-label col-sm-5">Gender:</label> 
      <div class="col-sm-7">
        <select class="form-control" id="id_gender" name="gender" placeholder="gender">
          <option value="" selected="selected">---------</option>
          <option value="M">MALE</option>
          <option value="F">FEMALE</option>
        </select>
      </div>
    <span class="error_message">{{ profile_form.gender.errors }}</span>
  </div>

  <div class="form-group">
    <label for="id_dob" class="control-label col-sm-5">Date of Birth:</label> 
    <div class="col-sm-7">
      <input class="form-control" id="id_dob" name="dob" type="text" data-mask="" data-inputmask="'alias': 'dd-mm-yyyy'"/>
    </div>
      <span class="error_message">{{ profile_form.dob.errors }}</span>
  </div>

  <div class="form-group">
    <label for="id_status" class="control-label col-sm-5">Marital Status:</label> 
    <div class="col-sm-7">
      <select class="form-control" id="id_status" name="status" placeholder="status">
        <option value="" selected="selected">---------</option>
        <option value="UNMARRIED">UNMARRIED</option>
        <option value="WIDOW/WIDOWER">WIDOW/WIDOWER</option>
        <option value="DIVORCED">DIVORCED</option>
      </select>
    </div>
    <span class="error_message">{{ profile_form.status.errors }}</span>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-5" for="id_religion">Religion:</label>
    <div class="col-sm-7">  
    {{ test1.religion|add_class:"form-control"|attr:"placeholder:religion" }}        
      
    </div>
    <span class="error_message">{{ profile_form.religion.errors }}</span>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-5" for="id_community">Community:</label>
    
    <div class="col-sm-7">
      {{ test1.community|add_class:"form-control"|attr:"placeholder:community" }}
    </div>
    <span class="error_message">{{ profile_form.community.errors }}</span>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-5" for="id_subcaste">Subcaste:</label>
    <div class="col-sm-7">          
      {{ test1.subcaste|add_class:"form-control"|attr:"placeholder:subcaste" }} 
    </div>   
    <span class="error_message">{{ profile_form.subcaste.errors }}</span>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-5" for="id_mother_tongue">Mother Tongue:</label>
    <div class="col-sm-7">          
      {{ test1.mother_tongue|add_class:"form-control"|attr:"placeholder:mother_tongue" }}
    </div>
    <span class="error_message">{{ profile_form.mother_tongue.errors }}</span>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-5" for="id_district">District:</label> 
    <div class="col-sm-7">          
      {{ test1.district|add_class:"form-control"|attr:"placeholder:district" }}
    </div>
    <span class="error_message">{{form.district.errors}}</span>          
  </div>

  <div class="form-group">
    <label class="control-label col-sm-5" for="id_mobile">Mobile Number:</label> 
    <div class="col-sm-7">          
      {{ test1.mobile|add_class:"form-control"|attr:"value:+919788568944"|attr:"placeholder:+91----------" }}
    </div>
    <span class="error_message">{{ profile_form.mobile.errors }}</span>          
  </div>

  <!-- Userform -->

  <div class="form-group">
    <label class="control-label col-sm-5" for="pwd">Email:</label>
    <div class="col-sm-7">          
      <input class="form-control" id="id_email" maxlength="75" name="email" placeholder="Email" type="email" />
    </div>
    <span class="error_message">{{ user_form.email.errors }}</span>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-5" for="email">Username:</label>
    <div class="col-sm-7">
      <input class="special form-control" id="id_username" name="username" placeholder="Username" type="text" />
    </div>
    <span class="error_message">{{ user_form.username.errors }}</span>  
    
  </div>

  <div class="form-group">
    <label class="control-label col-sm-5" for="pwd">Password:</label>
    <div class="col-sm-7">          
      <input class="form-control" id="id_password" maxlength="60" name="password" placeholder="Password" type="password" />
    </div>
    <span class="error_message">{{ user_form.password.errors }}</span>
  </div>

  

  
  
  
      <center>
        <div class="form-row">
            <button class="btn btn-success" type="submit" name="save" style="margin-bottom:10px;">
              <span class="glyphicon glyphicon-floppy-register"></span>&nbsp;Register
            </button>
        </div>
      </center>
        
    </form>
    </div>
    {% endblock %}